---
title: "Let's Make an Histogram"
author: "Otho Mantegazza"
date: "10/9/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Reproduce this Viz

```{r}

```


# Take Home

- Load data in R
- Everything in R is an object,
  - Tibbles and dataframes: R objects for rectangular data
- You can do anything with functions.
  - Tidyverse: a collection of function (package) for data analysis.

# Get the data

- need concept of function,
- concept of library
  
```{r}
library(tidyverse)
```

- need concept of dataframe/tibble
- need concept of rectangular data
  
```{r}
launches <-
  read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/launches.csv")
```
  
```{r}
launches %>% 
  ggplot(aes(x = launch_year,
             fill = agency_type)) +
  geom_bar(alpha = .8, width = 1) +
  labs(x = "",
       y = "Space Launches [n]",
       fill = "Agency Type:",
       title = "The Rise of Private Space Agencies") +
  scale_fill_manual(values = c("#27A6D3", "#FF6C0D", "#100089"),
                    guide = guide_legend(keyheight = .7, keywidth = 2)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5),
        legend.position = "top",
        axis.title.y = element_text(hjust = 1))
```

