---
title: "Code Club :)"
author: "Otho Mantegazza"
date: "`r Sys.Date()`"
output: 
  revealjs::revealjs_presentation:
    self_contained: true
    transition: slide
    theme: sky
    center: true
    css: custom-sky.css
    slide_level: 2
---

# Why Data Analysis for Biologists?

---

As a biologist, you'll often find yourself dealing with data.

Your experiment, be it phenotype measurements, gene expression analysis, genomic comparisons, will produce data. 

To understand your results and to explain them to others, you'll have to be able to **make sense of those data**.

# Why Data Analysis in R

---

No need, pick the software that suits your needs, use many of them and feel free to change.

**R** has some advantages: 

---

- It's professional and open source,
- It has great packages for data manipulation and visualization,
- It has powerful tools for communicating of your results,
- It has clear, extensive and user friendly documentation,
- It is powerful and easy to use.

# Learn by doing

---

Check out the [TidyTuesday](https://github.com/rfordatascience/tidytuesday), it's a weekly Social project on [Twitter](https://twitter.com/hashtag/TidyTuesday).

Publish TidyTuesdays frequently and you'll learn to analyze data in R, with a friendly and welcoming community.

---

<div style="float: right; padding: 5px; width: 45%;">
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
Ready for a *shiny* Sunday? ☀️<br>My son was sleeping at his grandparents, so what to do with all this free time? Made my very first <a href="https://twitter.com/hashtag/shiny?src=hash&amp;ref_src=twsrc%5Etfw">#shiny</a> using this week&#39;s <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a> data. <br><br>Code: <a href="https://t.co/jYNWu3DbNA">https://t.co/jYNWu3DbNA</a><br>Source: Bureau of Labor <a href="https://t.co/i9acX1m5g5">pic.twitter.com/i9acX1m5g5</a>
</p>
&mdash; Sil Aarts (@sil_aarts) 
<a href="https://twitter.com/sil_aarts/status/1104698411343855616?ref_src=twsrc%5Etfw">March 10, 2019</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

<div style="float: left; padding: 5px; width: 45%;">
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
Simple slope graph for <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a> illustrating the unethical and unnecessary pay gap in engineering. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/r4ds?src=hash&amp;ref_src=twsrc%5Etfw">#r4ds</a> Code: <a href="https://t.co/1BhlhPnYyC">https://t.co/1BhlhPnYyC</a> <a href="https://t.co/Pn0WjojXcW">pic.twitter.com/Pn0WjojXcW</a>
</p>
&mdash; Jake Kaupp (@jakekaupp)
<a href="https://twitter.com/jakekaupp/status/1103132855356608512?ref_src=twsrc%5Etfw">March 6, 2019</a></blockquote>
</div>

# Resources

## Bookdown

[Bookdown](https://bookdown.org/), has wonderful **books** on data analysis in R that you can consult openly online.

You might want to start from [R for Data Science](https://r4ds.had.co.nz/).

# Load your data into R

## Readr

If you want to analyze data in R, first you have to load them. 

You can do it with [readr](https://readr.tidyverse.org/) and [readxl](https://readxl.tidyverse.org/). These two packages cover two very common data formats: text rectangular data (csv, tsv) and excel data.

## Other kinds of data

You can load any kind of data into R, anwser are within reach on google. 


# Plot - Visualize your data

---

If you know how to visualize your data in graphs and plots you're half way there. You can use plots both to explore your data and to communicate your results.

You can use [ggplot2](https://ggplot2.tidyverse.org/), an R package for data visualization. You can find guides on how to use it  [on its website](https://ggplot2.tidyverse.org/) or in [this chapter of r4ds](https://r4ds.had.co.nz/data-visualisation.html).

## Use Plots to Explore and to Communicate

Keep in mind that you'll use plots for at least two reasons:

1. **Explore**: You can use plots to explore your data. Explorative plots should be produced quickly. (at expense of details)

2. **Communicate**: You can use plots to communicate your results to others. Plots for communication should be detailed and clear to everybody.

## Unleash your Inner Designer

Plots are real work of design: you make your results easy to understand and pleasurable to read merging a technical and a aesthetic presentation.


To make a nice plot, a nice data visualization you must make it clear and beautiful, balancing technical and aesthetics aspects.

## Learn from the best

<div style="float: right; padding: 5px; width: 45%;">
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">More new work! 🎉 My <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> is in the December issue of <a href="https://twitter.com/sciam?ref_src=twsrc%5Etfw">@SciAm</a>, revealing that &quot;Normal Body Temperature Is Surprisingly Less Than 98.6&quot; 🤒 <a href="https://t.co/FKpHLTlEpt">https://t.co/FKpHLTlEpt</a><br><br>It&#39;s always such a pleasure to work with <a href="https://twitter.com/ChristiansenJen?ref_src=twsrc%5Etfw">@ChristiansenJen</a> ^_^ We&#39;re even working on new piece for the March issue! <a href="https://t.co/Q3FCZxV4pn">pic.twitter.com/Q3FCZxV4pn</a>
</p>
&mdash; Nadieh Bremer (@NadiehBremer)
<a href="https://twitter.com/NadiehBremer/status/1077238474611118080?ref_src=twsrc%5Etfw">December 24, 2018</a>
</blockquote>
</div>


<div style="float: left; width: 45%;">
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">Climate change: where we are in seven charts - and what you can do to help  <a href="https://t.co/U5SEzICuIJ">https://t.co/U5SEzICuIJ</a> <a href="https://t.co/UNxNXcyRQU">pic.twitter.com/UNxNXcyRQU</a>
</p>
&mdash; Clara Guibourg (@cguibourg) <a href="https://twitter.com/cguibourg/status/1069509275280703488?ref_src=twsrc%5Etfw">December 3, 2018</a>
</blockquote>
</div>

# Wrangle - Manipulate your data

---

Sometime you have manipulate your datasets: you might want to filter them or to change, remove, add new columns to your data.

You can manipulate your data with [dplyr](https://dplyr.tidyverse.org/), learn how to use this R package [here](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html) or [in this chapter of r4ds](https://r4ds.had.co.nz/transform.html).

# Source

Tool: https://revealjs.com/#/
Source code: 
